verbose: 1

# Variables to manage the root file
root_folder_path: /sps/t2k/eleblevec/datasets/wcsimroot_datasets/hk
root_file_names:
  - electron_e_500_600_MeV/1/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_1.root
  - electron_e_500_600_MeV/2/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_2.root
  - electron_e_500_600_MeV/3/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_3.root
  - electron_e_500_600_MeV/4/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_4.root
  - electron_e_500_600_MeV/5/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_5.root
  - electron_e_500_600_MeV/6/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_6.root
  - electron_e_500_600_MeV/7/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_7.root
  - electron_e_500_600_MeV/8/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_8.root
  - electron_e_500_600_MeV/9/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_9.root
  - electron_e_500_600_MeV/10/HK_NomPMTs_SDO_500_600MeV_10kevents_e-_10.root
  - muon_e_500_600_MeV/1/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_1.root
  - muon_e_500_600_MeV/2/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_2.root
  - muon_e_500_600_MeV/3/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_3.root
  - muon_e_500_600_MeV/4/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_4.root
  - muon_e_500_600_MeV/5/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_5.root
  - muon_e_500_600_MeV/6/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_6.root
  - muon_e_500_600_MeV/7/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_7.root
  - muon_e_500_600_MeV/8/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_8.root
  - muon_e_500_600_MeV/9/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_9.root
  - muon_e_500_600_MeV/10/HK_NomPMTs_SDO_500_600MeV_10kevents_mu-_10.root

tree_name: 'root_event' # depending on wcsimroot_to_root


# Where to save the dataset containing the graphs
graph_folder_path: /sps/t2k/eleblevec/datasets/graph_datasets/e_mu_100keach_500_600Mev_X_t_c_Y_eventT

graph_file_names:
  - data.pt

# How many events to store (starting from event 0)
# for EACH .root file
# null means all the events
nb_datapoints: null

train_data_info: 
  keys : ['time', 'charge', 'hitx', 'hity', 'hitz']
  types: ['float64', 'float64', 'float16', 'float16', 'float16']

label_data_info:
  keys : ['eventType']
  types: ['int16']

edge_data_info:
  keys : ['hitx', 'hity', 'hitz']
  types: ['float16', 'float16', 'float16']

# If the data shoudl be stored as torch.Tensor. 
# For now only 'Yes' is supported
to_torch_tensor: True

# Transformations to apply only once to the data
# during the graph processing
# ARE YOU SURE THIS IS NOT SUPPOSED TO BE DONE IN CAVERNS ?
pre_transform:
  kNN: 
    k: 8
    num_workers: 4



        
