verbose: 1

# Variables to manage the root file
root_folder_path: /sps/t2k/eleblevec/datasets/wcsimroot_datasets/hk
root_file_names:
  - electron/1/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_1.root
  - electron/2/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_2.root
  - electron/3/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_3.root
  - electron/4/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_4.root
  - electron/5/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_5.root
  - electron/6/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_6.root
  - electron/7/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_7.root
  - electron/8/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_8.root
  - electron/9/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_9.root
  - electron/10/HK_NomPMTs_SDO_100_1kMeV_10kevents_e_10.root
  - pi0/1/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_1.root
  - pi0/2/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_2.root
  - pi0/3/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_3.root
  - pi0/4/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_4.root
  - pi0/5/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_5.root
  - pi0/6/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_6.root
  - pi0/7/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_7.root
  - pi0/8/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_8.root
  - pi0/9/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_9.root
  - pi0/10/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_10.root
  - electron/11/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_11.root
  - electron/12/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_12.root
  - electron/13/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_13.root
  - electron/14/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_14.root
  - electron/15/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_15.root
  - electron/16/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_16.root
  - electron/17/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_17.root
  - electron/18/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_18.root
  - electron/19/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_19.root
  - electron/20/HK_NomPMTs_SDO_100_1kMeV_10kevents_e-_20.root
  - pi0/11/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_11.root
  - pi0/12/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_12.root
  - pi0/13/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_13.root
  - pi0/14/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_14.root
  - pi0/15/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_15.root
  - pi0/16/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_16.root
  - pi0/17/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_17.root
  - pi0/18/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_18.root
  - pi0/19/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_19.root
  - pi0/20/HK_NomPMTs_SDO_100_1kMeV_10kevents_pi0_20.root

tree_name: 'root_event' # depending on wcsimroot_to_root


# Where to save the dataset containing the graphs
graph_folder_path: /sps/t2k/eleblevec/datasets/graph_datasets/e_pi0_200keach_100_1kMev_X_hits_t_c_Y_eventT_from1_20

graph_file_names:
  - data.pt

# How many events to store (starting from event 0)
# for EACH .root file
# null means all the events
nb_datapoints: null

train_data_info: 
  keys : ['time', 'charge']
  types: ['float32', 'float32']

label_data_info:
  keys : ['eventType']
  types: ['int16']

edge_data_info:
  keys : ['hitx', 'hity', 'hitz']
  types: ['float32', 'float32', 'float32']

# If the data shoudl be stored as torch.Tensor. 
# For now only 'Yes' is supported
to_torch_tensor: True

# Transformations to apply only once to the data
# during the graph processing
# ARE YOU SURE THIS IS NOT SUPPOSED TO BE DONE IN CAVERNS ?
pre_transform:
  kNN: 
    k: 8
    num_workers: 10

wandb:
  entity: erwanlbv
  project: database

  tags: 
    - e / pi0
    - 100_1000MeV
    - 400k
    - 400 GB RAM
    
  notes: Dataset e/pi0 400k f:t_c e:hits 

        
