verbose: 1

# Variables to manage the root file
root_folder_path: /sps/t2k/eleblevec/datasets/root_datasets/before_april/
root_file_names:
  - e_mu_500MeV_10events_each.root

tree_name: 'root_event' # depending on wcsimroot_to_root


# Where to save the dataset containing the graphs
graph_folder_path: /sps/t2k/eleblevec/datasets/graph_datasets/debug/

graph_file_names:
  - data.pt

# How many events to store (starting from event 0)
# for EACH .root file
# null means all the events
nb_datapoints: null

train_data_info: 
  keys : ['hitx','hity', 'hitz', 'time']
  types: ['float32', 'float32', 'float32', 'float32']

label_data_info:
  keys : ['eventType']
  types: ['int16']

edge_data_info:
  keys : ['hitx', 'hity', 'hitz']
  types: ['float32', 'float32', 'float32']

# If the data shoudl be stored as torch.Tensor. 
# For now only 'Yes' is supported
to_torch_tensor: True

# Transformations to apply only once to the data
# during the graph processing
# ARE YOU SURE THIS IS NOT SUPPOSED TO BE DONE IN CAVERNS ?
pre_transform:
  kNN: 
    k: 5
    num_workers: 1

wandb:
  entity: erwanlbv
  project: database

  tags: 
    - debug
    
  notes: Debug of plot_features et plot_model_summary